app/UI/Models/CustomerViewModel.cs
using Logic.Customers;

namespace UI.Models;

public class CustomerViewModel
{
    public IList<RentedItemViewModel> RentedItems { get; set; }

    public CustomerViewModel() { }

    public CustomerViewModel(Customer customer)
    {
        RentedItems = customer.RentedItems.ToList().Select(x => new RentedItemViewModel(x)).ToList();
    }
}

app/UI/Models/EquipmentViewModel.cs
using Logic.Customers;

namespace UI.Models;

public class EquipmentViewModel
{
    public long Id { get; set; }
    public string Name { get; set; }
    public string Type { get; set; }

    public EquipmentViewModel() {}

    public EquipmentViewModel(Equipment equipment)
    {
        Id = equipment.Id;
        Name = equipment.Name;
        Type = equipment.Type;
    }
}

app/UI/Models/ErrorViewModel.cs
namespace UI.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

app/UI/Models/RentEquipmentViewModel.cs
using Logic.Customers;

namespace UI.Models;

public class RentEquipmentViewModel
{
    public EquipmentViewModel Equipment { get; set; }
    public int? Days { get; set; }

    public RentEquipmentViewModel() {}

    public RentEquipmentViewModel(Equipment equipment, int? daysToRent=null)
    {
        Equipment = new EquipmentViewModel(equipment);
        Days = daysToRent;
    }
}

app/UI/Models/RentedItemViewModel.cs
using Logic.Customers;

namespace UI.Models;

public class RentedItemViewModel
{
    public RentEquipmentViewModel RentedItem { get; set; }
    public decimal Price { get; set; }

    public RentedItemViewModel() { }

    public RentedItemViewModel(RentedItem item)
    {
        RentedItem = new RentEquipmentViewModel(item.Equipment, item.RentalLength.Days);
        Price = item.Price;
    }
}

app/UI/Controllers/EquipmentController.cs
using Microsoft.AspNetCore.Mvc;
using Logic.Customers;
using UI.Models;
using UI.Utils;

namespace UI.Controllers;

public class EquipmentController : Controller
{
    private readonly EquipmentRepository _equipmentRepo;

    public EquipmentController(EquipmentRepository equipmentRepository)
    {
        _equipmentRepo = equipmentRepository;
    }

    [HttpGet]
    public IActionResult Index()
    {
        var equipment = _equipmentRepo.GetAllEquipment();
        var viewModels = equipment
            .Select(x => new EquipmentViewModel(x))
            .ToList();

        return View(viewModels);
    }

    [HttpGet]
    public IActionResult Rent(int id)
    {
        var equipmentToRent = _equipmentRepo.GetById(id);
        if (equipmentToRent.HasNoValue)
            return NotFound("No equipment found with ID " + id);

        var viewModel = new RentEquipmentViewModel(equipmentToRent.Value);

        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Rent(RentEquipmentViewModel rentEquipmentViewModel)
    {
        if (!rentEquipmentViewModel.Days.HasValue)
        {
            ModelState.AddModelError("Days", "Enter the no of days to rent the equipment");
            return View(rentEquipmentViewModel);
        }

        var rentalLengthResult = RentalLength.Create(rentEquipmentViewModel.Days.Value);
        if (rentalLengthResult.IsFailure)
        {
            ModelState.AddModelError("Days", rentalLengthResult.Error);
            return View(rentEquipmentViewModel);
        }

        var equipmentId = rentEquipmentViewModel.Equipment.Id;
        var equipmentToRent = _equipmentRepo.GetById(equipmentId);
        if (equipmentToRent.HasNoValue)
            return NotFound("No equipment found with ID " + equipmentId);

        var customerRepo = new CustomerRepository(HttpContext);
        var customer = customerRepo.GetCustomer();

        customer.RentEquipment(equipmentToRent.Value, rentalLengthResult.Value);

        customerRepo.SaveCustomer(customer);

        return RedirectToAction("Index");
    }
}

app/UI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using UI.Models;

namespace UI.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

app/UI/Controllers/RentedItemsController.cs
using Microsoft.AspNetCore.Mvc;
using UI.Utils;
using UI.Models;

namespace UI.Controllers;

public class RentedItemsController : Controller
{
    public RentedItemsController()
    {
    }

    public IActionResult Index()
    {
        var customerRepo = new CustomerRepository(HttpContext);
        var customer = customerRepo.GetCustomer();
        var customerVm = new CustomerViewModel(customer);

        return View(customerVm);
    }
}

app/UI/Views/Equipment/Index.cshtml
@model List<EquipmentViewModel>

@{
    ViewData["Title"] = "Equipment";
}

<h1>@ViewData["Title"]</h1>
<br>
<p>List of equipment to rent:</p>

<table class="table table-bordered table-striped" style="width: 100%;">
    <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var equipment in Model)
        {
            <tr>
                <td>@equipment.Name</td>
                <td>@equipment.Type</td>
                <td style="width: 1%; white-space:nowrap;">
                    <a asp-controller="Equipment" asp-action="Rent" asp-route-id="@equipment.Id" class="btn btn-primary">
                        <i class="bi bi-cart-plus"></i> &nbsp; Rent
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

app/UI/Views/Equipment/Rent.cshtml
@model RentEquipmentViewModel

@{
    ViewData["Title"] = $"Rent {Model.Equipment.Name}";
}

<form method="post" asp-controller="Equipment" asp-action="Rent">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">@ViewData["Title"]</h2>
            <hr />
        </div>
        <div class="mb-3">
            <input asp-for="Equipment.Id" class="form-control" style="width: 350px;" hidden/>
        </div>
        <div class="mb-3">
            <label>Equipment</label>
            <input asp-for="Equipment.Name" class="form-control" style="width: 350px;" readonly/>
        </div>
        <div class="mb-3">
            <label>Type</label>
            <input asp-for="Equipment.Type" class="form-control" style="width: 350px;" readonly/>
        </div>
        <div class="mb-3">
            <label>Days</label>
            <input asp-for="Days" class="form-control" style="width: 90px;" autofocus/>
            <span asp-validation-for="Days" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Rent</button>
        <a asp-controller="Equipment" asp-action="Index" class="btn btn-secondary">Back</a>
    </div>
</form>

app/UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

app/UI/Views/RentedItems/Index.cshtml
@model CustomerViewModel

@{
    ViewData["Title"] = "Rented items";
}

<h1>@ViewData["Title"]</h1>
<br/>

@if (!Model.RentedItems.Any())
{
    <p>Looks like you haven't rented any equipment. Go to our <a asp-controller="Equipment" asp-action="Index">list of equipment</a> to find some equipment to rent for yourself.</p>
}
else
{
    <table class="table table-bordered table-striped" style="width: 100%;">
        <thead>
            <tr>
                <th>Equipment</th>
                <th>Days</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.RentedItems)
            {
                <tr>
                    <td>@item.RentedItem.Equipment.Name</td>
                    <td>@item.RentedItem.Days</td>
                    <td>@item.Price €</td>
                </tr>
            }
            <tr class="fw-bold">
                <td>Total</td>
                <td>@Model.RentedItems.Sum(x => x.RentedItem.Days)</td>
                <td>@Model.RentedItems.Sum(x => x.Price) €</td>
            </tr>
        </tbody>
    </table>
}

app/UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/bootswatch-flatly.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Equipment" asp-action="Index">Online Construction Equipment Rental</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Equipment" asp-action="Index">Equipment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="RentedItems" asp-action="Index">Rented items</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - Online Construction Equipment Rental - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>